language: go

go:
  - tip

sudo: false

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert

script:
  - bash run_tests.sh
  - goveralls -coverprofile=coverage.out -service travis-ci

